// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wueyzrwzgnvchjxjghrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZXl6cnd6Z252Y2hqeGpnaHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyODAzNDEsImV4cCI6MjA0OTg1NjM0MX0.thax_G8pV_G1NXO4al3mBvTzFKrQwkt2p9hZjNJwDiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);